sudo: required
language: javascript
services:
  - docker

script:
  - docker build -t jkonovsky/statictemplate .

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "static-app-template"
  env: "Staticapptemplate-env"
  bucket_name: "elasticbeanstalk-us-east-2-524057441336"
  bucket_path: "static-app-template"
  on:
    branch: main

after_deploy:
  - echo "======== done deploying !!!! ========"
